const constants = {
  SEARCH_BY_TITLE: "SEARCH_BY_TITLE",
  SEARCH_BY_GENRE: "SEARCH_BY_GENRE",
  SEARCH_FOR_MOVIE: "SEARCH_FOR_MOVIE",
  SORT_BY_DATE: "SORT_BY_DATE",
  SORT_BY_RATING: "SORT_BY_RATING",
  GET_MOVIE_DETAILS: "GET_MOVIE_DETAILS"
};

export default constants;
